# Generated by Django 6.0.2 on 2026-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hours_per_week',
            field=models.CharField(default='4-8 hours', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_style',
            field=models.CharField(default='Video Courses', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_daily_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_new_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_weekly_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo_data',
            field=models.TextField(blank=True),
        ),
    ]
