# Generated by Django 6.0.2 on 2026-04-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('avg_salary_min', models.IntegerField()),
                ('avg_salary_max', models.IntegerField()),
                ('demand_level', models.CharField(max_length=50)),
                ('required_skills', models.JSONField(default=list)),
                ('job_titles', models.JSONField(default=list)),
                ('learning_duration', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(max_length=50)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='careers.career')),
            ],
        ),
    ]
