# Generated by Django 6.0.2 on 2026-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='countries',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='career',
            name='growth',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='career',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='career',
            name='path',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='career',
            name='salary_range',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='career',
            name='avg_salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='avg_salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='demand_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='career',
            name='learning_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
