# Generated by Django 6.0.2 on 2026-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='New Chat', max_length=100),
        ),
    ]
