# Generated by Django 6.0.2 on 2026-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=80, unique=True)),
                ('target_score', models.PositiveSmallIntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=80)),
                ('platform', models.CharField(max_length=80)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=220)),
                ('tags', models.JSONField(default=list)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('skill', 'title')},
            },
        ),
    ]
